image: node:16.16.0

stages:
  - eslint
  - build

eslint:
  stage: eslint
  script:
    - npm i --legacy-peer-deps
    - npm run lint

build:
  stage: build
  script:
    - npm i --legacy-peer-deps
    - npm run build
